# Generated by Django 3.2.6 on 2023-01-13 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtwoandhalf',
            name='bet_url',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='overtwoandhalf',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 22, 6, 4, 762978)),
        ),
    ]
