# Generated by Django 3.2.6 on 2023-01-19 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20230113_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtwoandhalf',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 13, 42, 57, 907572)),
        ),
    ]
