# Generated by Django 3.2.6 on 2023-01-20 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_overtwoandhalf_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.CharField(max_length=400)),
                ('awayTeam', models.CharField(max_length=400)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2023, 1, 20, 11, 11, 23, 557865))),
                ('btts_a', models.IntegerField()),
                ('btts_b', models.IntegerField()),
                ('championship', models.CharField(max_length=400)),
                ('bet_url', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='overtwoandhalf',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 11, 11, 23, 557865)),
        ),
    ]
